#ifndef QCONFIGURABLEDASHBOARD_CONFIGLOADER_H
#define QCONFIGURABLEDASHBOARD_CONFIGLOADER_H

namespace QCD {

    class ConfigLoader {

    };

} // QCD

#endif //QCONFIGURABLEDASHBOARD_CONFIGLOADER_H
