#ifndef QCONFIGURABLEDASHBOARD_BASEINTERFACE_H
#define QCONFIGURABLEDASHBOARD_BASEINTERFACE_H

namespace QCD {

    class BaseInterface {

    };

} // QCD

#endif //QCONFIGURABLEDASHBOARD_BASEINTERFACE_H
